language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache: npm
install:
  - npm install --ignore-scripts # Ignore Botmation CLI
  - npm rebuild puppeteer # but, we didn't want to ignore this postinstall script
script:
  - jest