language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache: npm
install:
  - npm install --ignore-scripts # Ignore Botmation CLI (no need for User walkthrough)
  - npm run createbaseconfigfile # but, create the config file, was defaults
  - npm rebuild puppeteer # and run the scripts for puppeteer
script:
  - jest