name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting an issue! We greatly appreciate it. We\'ll follow up as soon as we can.'
        pr-message: 'Thank you for submitting a Pull Request! If you need any assistance, do not hesitate to @ mrWh1te on Github, the Technical Lead of this project.'